AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

# Tip: add rubocop-rspec, rubocop-performance, rubocop-rails in the future
