# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Rails API
gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'

# JSON
gem 'jbuilder', '~> 2.11'

# Authentication
gem 'jwt', '~> 2.7'
gem 'bcrypt', '~> 3.1'

# CORS
gem 'rack-cors', '~> 2.0'

# HTTP Client (for inter-service communication)
gem 'faraday', '~> 2.7'

# WebSocket (ActionCable)
gem 'redis', '~> 5.0'

# Background Jobs
gem 'concurrent-ruby', '~> 1.2'

# Timezone
gem 'tzinfo-data'

# Boot optimization
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug'
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'webmock', '~> 3.18'
end
